name: UI Tests

on: [push]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Run UI-tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
            npm install
            npm run test

      - name: Generate allure report
        run: |
            npm install -g allure-commandline --save-dev
            allure generate allure-results --clean -o allure-report
            allure open allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report